### ISSUE TITLE
[BUG REPORT] Missing Latest Reviews in Course Page for GA

### ISSUE THREAD

**Issue by chung-chris** [oms-fyi/reviews#102]
**Describe the bug**
The latest review date for Graduate Algorithms has a date of 11/4/2023 as of this writing: https://www.omscentral.com/courses/introduction-to-graduate-algorithms/reviews

However, there are more recent reviews for this course in the Top 100 recent reviews: https://www.omscentral.com/reviews/recent

**Desktop (please complete the following information):**

- OS: Ubuntu 22.04
- Browser: Chrome
- Version 122

**Comment by m4ttsch** [comment]
The most recent is 3/4/2024.
