### ISSUE TITLE
[EDIT] Special Topics: Systems Design For Cloud Computing

### ISSUE THREAD

**Issue by abhijeetd1** [oms-fyi/reviews#104]
**What information is incorrect or missing?**
For example, syllabus, textbooks, or description.

Updated Course Name to match GT official name

**Comment by m4ttsch** [comment]
What is the GT Official name?

**Comment by abhijeetd1** [comment]
Systems Design For Cloud Computing is the official GT name.   It was mentioned as System Issues for Cloud Computing.

**Comment by m4ttsch** [comment]
Updated! Thank you ⭐
