### ISSUE TITLE
[BUG REPORT] Cannot develop locally

### ISSUE THREAD

**Issue by ndd7xv** [oms-fyi/reviews#90]
**Describe the bug**
Was trying to poke around the code base, but it seems I cannot do that without a Sanity configuration.

**To Reproduce**

1. `git clone https://github.com/oms-tech/reviews.git`
2. `npm install`
3. `npm run dev`
4. Navigate to http://localhost:3000 as specified by stdout
5. See server error in screenshot 

**Expected behavior**
I'm assuming that I would see a local version of omscentral.com

**Screenshots**
![image](https://github.com/oms-tech/reviews/assets/57812141/f28624da-243a-4833-a335-08da80d65d8d)

**Desktop (please complete the following information):**

- OS: Fedora 36
- Browser: Firefox
- Version 112.0.1

Sorry if there's a trivial fix, I'm not super familiar with frontend/js or ts stuff. It seems like I need to pass in `NEXT_PUBLIC_SANITY_PROJECT_ID` and `NEXT_PUBLIC_SANITY_DATASET` as env variables?

**Comment by m4ttsch** [comment]
Yeah I don't expose access to this atm because my credit card is linked to the sanity account and is charged by usage. I need to think of a good way to fix this. Maybe a small static dataset...

**Comment by m4ttsch** [comment]
Hey! After more consideration, I don't think it's a huge issue to give folks read access to the data. If I see that I am hitting limits, I add some authorization around the API and be more selective with who I let develop locally.

Dataset: *production*
Project ID: *3yw11hu2*

Cheers! ⭐
