### ISSUE TITLE
[BUG REPORT] New CORS Policy blocks access to reviews

### ISSUE THREAD

**Issue by logic-tonic** [oms-fyi/reviews#92]
Hello, I've been using (and attributing) [review data from your site](https://www.omscentral.com/_next/data/TD61NkXhGHooJ12py3vhc/index.json) to make omscscourseplanner.com, which has been helping a lot of students to plan their OMSCS courselist. The site has recently broken because of a CORS policy. Have you updated your CORS policy recently? Was it on purpose, to block people from accessing the data?

**Comment by m4ttsch** [comment]
I don't remember updating anything related to CORS recently... but, uh, I wish you would have told me you wanted to use the data. You can hit the sanity endpoint directly for reads. No need to read in that janky JSON.

Dataset: production
Project ID: 3yw11hu2

Cheers! ⭐

ALSO, omscscourseplanner.com is dope! I've recently acquired <oms.fyi>, so if you'd like to host alongside the reviews (and eventually the merged in course notes from <omscs-notes.com>, LMK!

- Matt

**Comment by logic-tonic** [comment]
I tried rewriting my code to accept the sanity endpoint instead (for course info), but it doesn't have the attached difficulty/workload/rating summaries for each course. Is there any chance you could update the CORS option to allow me to read the initial JSON file that I was reading? It would be ideal if I could not change up my code

**Comment by m4ttsch** [comment]
Hmmm, I definitely haven't changed anything on the Vercel side...

**Comment by logic-tonic** [comment]
Had you removed any other CORS options recently?

**Comment by m4ttsch** [comment]
I transferred my domain to a new registrar but that's upstream of the webserver so I don't think that's it. If we can't resolve now, I can give you a dump of the data so you can move forward until we investigate further.

**Comment by logic-tonic** [comment]
Can you try adding https://omscscourseplanner.com/  to your Access-Control-Allow-Origin header? If that doesn't work, that dump would be great, thanks so much!

**Comment by logic-tonic** [comment]
Please provide the data dump if you can't add the site to the header

**Comment by m4ttsch** [comment]
Hey sorry for the late reply. Been swamped. I will add your site via [this guide](https://vercel.com/guides/how-to-enable-cors)

**Comment by m4ttsch** [comment]
Alternatively, feel free to submit a PR.

**Comment by logic-tonic** [comment]
Hey, were you able to add the site to the guide? If not, please provide a data dump, hundreds of users have been visiting a broken site and I just need to get it working

**Comment by m4ttsch** [comment]
Hey, I just looked through your source code. This has absolutely nothing to do with CORS. You can't rely on the [URL](https://www.omscentral.com/_next/data/TD61NkXhGHooJ12py3vhc/index.json) you posted in your first comment. The `TD61NkXhGHooJ12py3vhc` bit is not stable. It changes every deployment. I just hadn't deployed in a while.

**Comment by logic-tonic** [comment]
Hey, I usually update the link when you deploy (not the best solution but I haven't found the time to improve it). Usually, fixing the 404 leads to the CORS error. But I just updated the link and saw that you fixed the CORS error! Thanks so much!

**Comment by m4ttsch** [comment]
Glad you're all squared away. Let me know if you want to collaborate on any new features in the future!

**Comment by logic-tonic** [comment]
Thanks Matt! 

FYI it seems that the CORS error is back: https://omscscourseplanner.com/
It was working normally a few days ago, did something change on your end?
